name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  KUBE_URL: ${{ secrets.KUBE_URL }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
  AUTHORITY: ${{ SECRETS.AUTHORITY }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      
#       - name: Build images
#         run: |
#           docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASS
#           make imgs

      - name: Deploy
        run: |
          kubectl config set-cluster yc-managed-k8s-caturihqkb4koc79r3al --server="$KUBE_URL" --certificate-authority-data="$AUTHORITY"
          kubectl config set-credentials thesawisthelaw --token="$KUBE_TOKEN"
          kubectl config set-context yc-managed-k8s-caturihqkb4koc79r3al --cluster=yc-managed-k8s-caturihqkb4koc79r3al --user=thesawisthelaw
          kubectl config use-context yc-managed-k8s-caturihqkb4koc79r3al
          helm delete services
          helm install services k8s/services-chart/
          sleep 60
        
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
