name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master

env:
  DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
  KUBE_URL: ${{ secrets.KUBE_URL }}
  KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Build binaries
        run: |
          make makeJars

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: thesawisthelaw
          password: $DOCKERHUB_PASS
      
      - name: Build and push gateway
        uses: docker/build-push-action@v3
        with:
          context: /src/gateway
          push: true
          tags: thesawisthelaw/gateway:latest
          
      - name: Build and push cars
        uses: docker/build-push-action@v3
        with:
          context: /src/cars
          push: true
          tags: thesawisthelaw/cars:latest
          
      - name: Build and push rental
        uses: docker/build-push-action@v3
        with:
          context: /src/rental
          push: true
          tags: thesawisthelaw/rental:latest
          
      - name: Build and push payment
        uses: docker/build-push-action@v3
        with:
          context: /src/payment
          push: true
          tags: thesawisthelaw/payment:latest

      - name: Deploy
        run: |
          kubectl config set-cluster cars-service-cluster --server="$KUBE_URL" --insecure-skip-tls-verify=true
          kubectl config set-credentials admin --token="$KUBE_TOKEN"
          kubectl config set-context default --cluster=cars-service-cluster --user=admin
          kubectl config use-context default
          cd k8s && helm delete services && helm install services services-chart/
          sleep 45
        
      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
